//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Formula_1_Media_Handler.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://thetvdb.com/series/formula-1/allseasons/official")]
        public string TvdbURL {
            get {
                return ((string)(this["TvdbURL"]));
            }
            set {
                this["TvdbURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1656889656")]
        public long LastUpdate {
            get {
                return ((long)(this["LastUpdate"]));
            }
            set {
                this["LastUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2592000")]
        public double UpdateInterval {
            get {
                return ((double)(this["UpdateInterval"]));
            }
            set {
                this["UpdateInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Downloads\\_rss\\F1")]
        public string Source {
            get {
                return ((string)(this["Source"]));
            }
            set {
                this["Source"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Media\\TV Shows\\Formula 1")]
        public string Destination {
            get {
                return ((string)(this["Destination"]));
            }
            set {
                this["Destination"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FirstTimeSetup {
            get {
                return ((bool)(this["FirstTimeSetup"]));
            }
            set {
                this["FirstTimeSetup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:34265/")]
        public string QBWebURI {
            get {
                return ((string)(this["QBWebURI"]));
            }
            set {
                this["QBWebURI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Avalerion")]
        public string QBLogin {
            get {
                return ((string)(this["QBLogin"]));
            }
            set {
                this["QBLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("qb2#bfT@09")]
        public string QBPassword {
            get {
                return ((string)(this["QBPassword"]));
            }
            set {
                this["QBPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("43200000")]
        public double TimerCheckMonitored {
            get {
                return ((double)(this["TimerCheckMonitored"]));
            }
            set {
                this["TimerCheckMonitored"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300000")]
        public double TimerCheckTorrent {
            get {
                return ((double)(this["TimerCheckTorrent"]));
            }
            set {
                this["TimerCheckTorrent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0 0 10 1/1 * ? *")]
        public string Cron_CheckMonitored_Job {
            get {
                return ((string)(this["Cron_CheckMonitored_Job"]));
            }
            set {
                this["Cron_CheckMonitored_Job"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0 0/1 * 1/1 * ? *")]
        public string Cron_CheckTorrents_Job {
            get {
                return ((string)(this["Cron_CheckTorrents_Job"]));
            }
            set {
                this["Cron_CheckTorrents_Job"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0 0 14 5 1/1 ? *")]
        public string Cron_MetadataUpdate_Job {
            get {
                return ((string)(this["Cron_MetadataUpdate_Job"]));
            }
            set {
                this["Cron_MetadataUpdate_Job"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long Cron_CheckMonitored_LastRun {
            get {
                return ((long)(this["Cron_CheckMonitored_LastRun"]));
            }
            set {
                this["Cron_CheckMonitored_LastRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long Cron_CheckTorrents_LastRun {
            get {
                return ((long)(this["Cron_CheckTorrents_LastRun"]));
            }
            set {
                this["Cron_CheckTorrents_LastRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long Cron_MetadataUpdate_LastRun {
            get {
                return ((long)(this["Cron_MetadataUpdate_LastRun"]));
            }
            set {
                this["Cron_MetadataUpdate_LastRun"] = value;
            }
        }
    }
}
